### Numpy 연습

In [64]:
import numpy as np

In [2]:
def genNewTempDataFile():
    dataFileName = 'daegu_temp_20years.csv'     # 20년간 대구의 최고기온, 최저기온, 평균기온을 갖는 데이터를 읽어옴
    newFileName = 'new_daegu_temp.csv'          # 새로 write할 파일 명을 'new_daegu_temp.csv'로 설정
    
    read_f = open(dataFileName, 'r')
    write_f = open(newFileName, 'w')
    
    while True:
        line = read_f.readline()
        if not line:
            break
        
        splitData = line.split(',')
        
        skipWriting = False
        if len(splitData) == 5 and splitData[1].isnumeric():
            splitData[0] = splitData[0].replace('-', '')          # splitData[0]의 원소(날짜)의 형식 변경. ex) 2015-06-17 --> 20150617 
            
            for data in splitData:                          
                try:                                              # splitData를 float형식으로 변경. 
                    float(data)
                except ValueError:                                # ValueError 발생 시 예외처리 후 출력.
                    print("에러 : ", splitData[0])
                    skipWriting = True
                    break
                    
            if not skipWriting:                                   # skipWriting이 True일 경우(ValueError가 없을 경우) splitData를 , 로 결합하고 새로 write
                newData = ','.join(splitData)
                write_f.write(newData)

    write_f.close()
    read_f.close()
            


In [6]:
dataFileName = 'new_daegu_temp.csv'
tempdata = np.loadtxt(dataFileName, delimiter = ',')

In [7]:
tempdata.size

36665

In [8]:
tempdata.shape

(7333, 5)

In [3]:
genNewTempDataFile()

에러 :  20130930
에러 :  20170729


## 최고온도 구하기
    * 날짜(0), 지점(1), 평균온도(2), 최저온도(3), 최고온도(4)

In [9]:
np.max(tempdata)

20200720.0

In [35]:
tempdata[:,4]

array([33. , 23.4, 28.3, ..., 27.6, 28. , 32.8])

In [12]:
np.max(tempdata[:,4])

39.2

## 최저 기온

In [14]:
np.min(tempdata[:,3])

-13.9

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

### 최고 기온과 최저 기온이 발생한 날짜는??

In [17]:
np.argmax(tempdata[:,4])

6608

In [19]:
tempdata[6608, 0].astype(np.int)

20180727

In [21]:
np.argmin(tempdata[:,3])

6427

In [22]:
tempdata[6427,0].astype(np.int)

20180127

In [27]:
# 각 축의 max 값 출력
# axis = 0 : 열방향, 위에서 아래로 수직방향
np.max(tempdata, axis = 0)

array([2.020072e+07, 1.430000e+02, 3.310000e+01, 2.860000e+01,
       3.920000e+01])

In [28]:
np.argmax(tempdata, axis=0)         # 각 축의 max 값을 갖는 index 출력

array([7332,    0, 6607, 6608, 6608], dtype=int64)

In [29]:
max_data = np.argmax(tempdata, axis=0)

In [31]:
tempdata[max_data[4], 0]            # max_data[4] : 

20180727.0

In [32]:
np.max(tempdata, axis=0)[2]

33.1

## 최고 기온, 최저기온 top 10 날짜와 온도 구하기

In [36]:
len(tempdata)       # tempdata의 길이 출력

7333

In [ ]:
def getTop10Temp(tempData):
    highTempTop10 = {}
    lowTempTop10 = {}
    for i in range(10):
        maxTempIndex = np.argmax(tempData[:,4])
        highestTemp = tempData[maxTempIndex, 4]
        highestTempDate = tempData[maxTempIndex, 0].astype(np.int)

        tempData = np.delete(tempData, maxTempIndex, axis=0)

        minTempIndex = np.argmin(tempData[:,3])
        lowestTemp = tempData[minTempIndex, 3]
        lowestTempDate = tempData[maxTempIndex, 0].astype(np.int)

        

In [63]:
#max_top10temp
#max_top10date

max_top10 = {}
min_top10 = {}

for x in range(0,10):   # 10개의 값 추출
    maxTempIndex = np.argmax(tempdata[:,4])                     # maxTempIndex 에 tempdat의 4번째 값(최대 온도)중 최대값을 갖는 인덱스를 저장
    highestTemp = tempdata[maxTempIndex,4]                      # 최대온도 최대값을 갖는 인덱스의 4번째 열의 값(최대 온도 값)을 highestTemp에 저장
    highestTempDate = tempdata[maxTempIndex, 0].astype(np.int)  # 최대값의 날짜(tempdata[maxTempIndex,0])를 int형으로 저장
    

    tempdata = np.delete(tempdata, maxTempIndex, axis=0)    # max값 가진 index를 삭제

    minTempIndex = np.argmax(tempdata[:,3])
    lowestTemp = tempdata[minTempIndex,3]
    lowestTempDate = tempdata[minTempIndex, 0].astype(np.int)

    tempdata = np.delete(tempdata, minTempIndex, axis=0)    # min값 가진 index 삭제 후 다시 저장

    max_top10[highestTempDate] = highestTemp        #key 값으로 highestTempDate, data를 highestTemp 를 가진 Dict 원소 추가
    min_top10[lowestTempDate] = lowestTemp          #key 값으로 lowestTempDate, data를 lowestTemp 를 가진 Dict 원소 추가 

print(max_top10)
print(min_top10)



{20180801: 37.5, 20130819: 37.4, 20140531: 37.4, 20060815: 37.2, 20170713: 37.2, 20180716: 37.2, 20180802: 37.2, 20060814: 37.1, 20180725: 37.1, 20180808: 37.1}
{20180805: 28.6, 20130808: 28.2, 20010803: 27.8, 20120731: 27.8, 20120802: 27.7, 20110727: 27.5, 20140725: 27.5, 20170721: 27.5, 20000722: 27.4, 20010723: 27.4}


### 20년간 각 연도별 최고 기온, 최저기온, 최고 평균기온, 최저 평균을 구해보시오