## Numpy

- python의 배열 연산보다 훨씬 빠름
- 벡터 연산을 지원

In [1]:
import numpy as np

array() : 리스트로부터 ndarray 생성

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
np.array(1, 2, 3)

ValueError: only 2 non-keyword arguments accepted

In [4]:
a = np.array([1, 2, 3, 4, 5])

In [5]:
type(a)

numpy.ndarray

In [8]:
a.ndim      #차원을 출력

1

In [11]:
a.dtype     # 입력되어있는 데이터의 타입을 출력

dtype('int32')

In [12]:
a.size      # a에 들어가 있는 원소의 개수 확인 가능

5

NameError: name '능' is not defined

In [14]:
a.shape     # tuple로 a 가 어떤 형태로 구성되어 있는지 확인

(5,)

In [16]:
a2 = np.array([ [1,2,3], [5,6,7] ])

In [17]:
a2

array([[1, 2, 3],
       [5, 6, 7]])

In [18]:
a2.dtype

dtype('int32')

In [19]:
a2.size

6

In [20]:
a2.shape

(2, 3)

In [21]:
a3 = np.array([1, 2, 3], dtype=float)

In [22]:
a3.dtype

dtype('float64')

In [24]:
np.zeros(10)        # 기본적으로 실수형 값으로 저장

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [29]:
np.ones([3,5])
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### np.array는 기본적으로 같은 타입의 데이터가 들어간다고 생각하고 동작하기 떄문에 파이썬의 리스트보다 빠름. 파이썬의 리스트는 각기 다른 원소가 들어 갈 수 있다고 생각하기 때문.

In [28]:
np.full((4,5), 7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [31]:
np.arange(10)       # 얘는 ndarray로 만듦.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
list(range(10))     # 얘는 리스트로 만듦

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [33]:
np.arange(1,5)

array([1, 2, 3, 4])

In [34]:
np.arange(1, 100, 3)

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49,
       52, 55, 58, 61, 64, 67, 70, 73, 76, 79, 82, 85, 88, 91, 94, 97])

In [3]:
np.arange(0, 10, 0.1)       # python의 range는 소수점 단위로 증가하는 리스트를 만들 수 없음.

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ,
       9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [4]:
list(range(0, 10, 0.1))         # 실수값을 사용할 수 없다!!!

TypeError: 'float' object cannot be interpreted as an integer

In [38]:
#끝에 숫자(100)이 무조건 포함되어 있음
np.linspace(0, 100, 5, dtype = int) #0부터 100까지 다섯등분하기!!

array([  0,  25,  50,  75, 100])

In [39]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [40]:
np.linspace(0, 10, 5, dtype = int)

array([ 0,  2,  5,  7, 10])

In [43]:
np.random.random((3,4))     # 무작위로 0~1 사이의 값 생성

array([[0.5176073 , 0.97497249, 0.1987847 , 0.57752076],
       [0.00809243, 0.11608603, 0.1280259 , 0.74155839],
       [0.74871418, 0.43397955, 0.71740366, 0.80001958]])

In [78]:
np.random.randint(0, 10, (3,3) )   # 10은 포함되지 않음. int로 이루어진 배열 생성

array([[1, 8, 6],
       [7, 4, 9],
       [9, 8, 6]])

>정규분포, 평균값 0, 표준편차 1

In [79]:
np.random.normal(0, 1, (3,3))

array([[ 1.08109743, -0.61657858,  0.08383522],
       [-1.32123599,  0.46517989,  1.19297404],
       [-0.12993311,  2.59128536, -0.70178753]])

In [82]:
np.random.seed(0)       #파이썬에서는 시드 값이 계속 자동으로 변함. seed함수를 이용하여 고정 가능.

arr1 = np.random.randint(10, size = 6)
arr2 = np.random.randint(10, size = (2,3))

In [83]:
arr1

array([5, 0, 3, 3, 7, 9])

In [85]:
arr2

array([[3, 5, 2],
       [4, 7, 6]])

In [88]:
arr1[-1]        # arr1의 마지막 값은 9

9

In [94]:
arr3 = np.arange(20)

In [93]:
np.arange(20).reshape(4,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [95]:
arr5 = arr3.reshape(2,-1)
arr5

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [96]:
list1 = [0, 1, 2, 3, 4]
list2 = [4, 5, 6, 7, 8]

In [97]:
list1

[0, 1, 2, 3, 4]

In [98]:
list2

[4, 5, 6, 7, 8]

In [102]:
[list1, list2]

[[0, 1, 2, 3, 4], [4, 5, 6, 7, 8]]

In [103]:
arr6 = np.concatenate([list1, list2])

In [104]:
arr6

array([0, 1, 2, 3, 4, 4, 5, 6, 7, 8])

In [105]:
arr7 = arr6.reshape(2, -1)

In [106]:
arr7

array([[0, 1, 2, 3, 4],
       [4, 5, 6, 7, 8]])

In [107]:
arr8 = np.concatenate([arr7, arr7]) # 행 방향으로 합침.

In [108]:
arr8

array([[0, 1, 2, 3, 4],
       [4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4],
       [4, 5, 6, 7, 8]])

In [110]:
np.concatenate([arr7, arr7], axis = 1)


array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [4, 5, 6, 7, 8, 4, 5, 6, 7, 8]])

In [111]:
np.vstack([arr7, arr7])     # 수직으로 쌓기

array([[0, 1, 2, 3, 4],
       [4, 5, 6, 7, 8],
       [0, 1, 2, 3, 4],
       [4, 5, 6, 7, 8]])

In [112]:
np.hstack([arr7, arr7])     # 수평으로 쌓기

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [4, 5, 6, 7, 8, 4, 5, 6, 7, 8]])

## Numpy 내장함수 --> Universal Funcrion

In [114]:
arr7

array([[0, 1, 2, 3, 4],
       [4, 5, 6, 7, 8]])

In [117]:
np.sum(arr7)        # 모든 원소의 합 출력

40

In [121]:
np.sum(arr7, axis = 0)     # 행 방향(위에서 아래로 )으로 연산

array([ 4,  6,  8, 10, 12])

In [122]:
np.sum(arr7, axis = 1)

array([10, 30])

In [126]:
np.min(arr7, axis = 0)      # 행 방향으로의 최솟값


array([0, 1, 2, 3, 4])

In [127]:
np.max(arr7, axis = 0)

array([4, 5, 6, 7, 8])


### 기본 연산

elementwise : 요소 단이로 연산이 이루어진다

In [128]:
a = np.array([20, 30, 40, 50])

In [129]:
b = np.arange(4)

In [130]:
a

array([20, 30, 40, 50])

In [131]:
b

array([0, 1, 2, 3])

In [132]:
a -b

array([20, 29, 38, 47])

In [133]:
a + 10

array([30, 40, 50, 60])

In [135]:
b ** 3      # 각각의 원소를 세제곱. 

array([ 0,  1,  8, 27], dtype=int32)

In [138]:
a < 40      # 각각의 요소를 비교하여 결과값을 array로 출력

array([ True,  True, False, False])

In [140]:
A = np.array([[1,1], [0,1]])
B = np.array([[2,0], [3,4]])

In [143]:
print(A)
print()
print(B)

[[1 1]
 [0 1]]

[[2 0]
 [3 4]]


In [146]:
# matrix 곱은 요소끼리 곱함. elementwise
#실제 행렬이 곱하는 방식과는 다름!!!!!!!!!!!!!

A * B       


array([[2, 0],
       [0, 4]])

In [149]:
# 실제 행렬이 하는 곱 1
A @ B

array([[5, 4],
       [3, 4]])

In [148]:
# 실제 행렬이 하는 곱 2
A.dot(B)

array([[5, 4],
       [3, 4]])

In [156]:
arr10 = np.random.randint(10, size = (5,5))

In [157]:
arr10

array([[1, 3, 3, 3, 7],
       [0, 1, 9, 9, 0],
       [4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1]])

In [158]:
arr11 = arr10

In [159]:
arr11

array([[1, 3, 3, 3, 7],
       [0, 1, 9, 9, 0],
       [4, 7, 3, 2, 7],
       [2, 0, 0, 4, 5],
       [5, 6, 8, 4, 1]])

In [160]:
arr11[0,0] = 100


In [161]:
arr11

array([[100,   3,   3,   3,   7],
       [  0,   1,   9,   9,   0],
       [  4,   7,   3,   2,   7],
       [  2,   0,   0,   4,   5],
       [  5,   6,   8,   4,   1]])

In [163]:
# arr11 = arr10 으로 할당 후 arr11의 값을 변경했는데 arr10의 값도 바뀜
# arr11 = arr10 의 연산을 할때 arr10[0,0]은 특정값을 갖고 있는 공간의 주소가 들어 가 있는데 그 주소를 arr11에도 똑같이 넣어줌.
# 따라서 arr11[0][0]의 값을 변경하면 해당된 주소를 참조하여 그 주소의 값이 바뀌기 때문에 arr10[0][0] 의 값도 똑같이 변경되어있음.
arr10           


array([[100,   3,   3,   3,   7],
       [  0,   1,   9,   9,   0],
       [  4,   7,   3,   2,   7],
       [  2,   0,   0,   4,   5],
       [  5,   6,   8,   4,   1]])

In [171]:
# arr10을 deep copy. arr10의 값을 갖고 있는 똑같은 배열을 새로 생성 

arr12 = arr10.copy()        


In [165]:
arr12

array([[100,   3,   3,   3,   7],
       [  0,   1,   9,   9,   0],
       [  4,   7,   3,   2,   7],
       [  2,   0,   0,   4,   5],
       [  5,   6,   8,   4,   1]])

In [166]:
arr12[0][1] = 200

In [167]:
arr12

array([[100, 200,   3,   3,   7],
       [  0,   1,   9,   9,   0],
       [  4,   7,   3,   2,   7],
       [  2,   0,   0,   4,   5],
       [  5,   6,   8,   4,   1]])

In [172]:
# arr10[0][1] 은 변경 x. arr12와 arr10은 다른 배열이 됨
arr10           

array([[100,   3,   3,   3,   7],
       [  0,   1,   9,   9,   0],
       [  4,   7,   3,   2,   7],
       [  2,   0,   0,   4,   5],
       [  5,   6,   8,   4,   1]])

In [175]:
# 두 배열의 값이 같은지 확인
arr10 is arr11

True

In [176]:
arr10 is arr12

False

## 2020_07_23

In [2]:
a = np.random.randint(1, 10, (3,4))

In [3]:
a

array([[8, 4, 3, 6],
       [6, 8, 3, 1],
       [1, 7, 9, 5]])

In [4]:
a > 5

array([[ True, False, False,  True],
       [ True,  True, False, False],
       [False,  True,  True, False]])

In [5]:
b = a>5

In [6]:
np.logical_and(a > 3, a < 8)

array([[False,  True, False,  True],
       [ True, False, False, False],
       [False,  True, False,  True]])

In [8]:
a

array([[8, 4, 3, 6],
       [6, 8, 3, 1],
       [1, 7, 9, 5]])

In [9]:
np.sum(a>3, axis = 1)       # 3보다 큰 원소가 몇 개 있는지

array([3, 2, 3])

## boolean index

* 특정 조건을 만족하는 값을 추출할 때 사용!!

In [10]:
a[a>3]      # 1차원 배열로 되어있다

array([8, 4, 6, 6, 8, 7, 9, 5])

In [15]:
a = np.random.randint(0,100,100).reshape(10,-1)

In [16]:
b = a>50

In [17]:
b

array([[False, False, False,  True,  True, False,  True,  True,  True,
         True],
       [ True,  True, False,  True, False,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True, False, False,  True,  True, False,
        False],
       [ True,  True, False,  True, False,  True,  True, False,  True,
        False],
       [False,  True, False,  True,  True, False, False, False,  True,
        False],
       [ True,  True,  True, False, False, False,  True, False, False,
        False],
       [ True,  True, False,  True,  True,  True,  True, False, False,
         True],
       [ True, False,  True, False,  True, False, False,  True, False,
        False],
       [False,  True,  True, False,  True, False,  True, False,  True,
        False],
       [False, False,  True, False,  True, False,  True, False, False,
        False]])

In [18]:
np.sum(b)

52

In [19]:
b.astype(np.int)

array([[0, 0, 0, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 0, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 1, 0, 1, 1, 0, 1, 0],
       [0, 1, 0, 1, 1, 0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0, 0, 1, 0, 0, 0],
       [1, 1, 0, 1, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 0, 1, 0, 0, 1, 0, 0],
       [0, 1, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 0, 1, 0, 0, 0]])

In [20]:
a[a>50]

array([60, 97, 87, 80, 98, 81, 82, 85, 68, 99, 62, 90, 55, 99, 64, 89, 62,
       85, 82, 85, 56, 80, 63, 67, 59, 72, 65, 61, 93, 87, 58, 76, 88, 94,
       66, 60, 71, 82, 51, 81, 76, 95, 95, 52, 60, 67, 54, 71, 72, 79, 66,
       57])

## Fancy index

* numpy array를 index calue로 사용해서 값을 추출

In [22]:
a = np.arange(12).reshape(3,4)

In [23]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [24]:
row = np.array([0,1,2])

In [25]:
col = np.array([1,2,3])

In [26]:
a[row]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [28]:
row

array([0, 1, 2])

In [29]:
col

array([1, 2, 3])

In [30]:
row3 = np.array([4,7,8])

In [32]:
a[row3]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [33]:
a.take(row3)

array([4, 7, 8])

## 단위 행렬 : identity

In [34]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### 단축키 : 실행 (shift + enter, ctrl + enter)

### 함수의 설명을 볼 수 있는 단축키 : shift + tab

In [35]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [36]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [37]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [38]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [39]:
np.eye(6, k= 2)     # k는 대각선 시작의 위치를 정함

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
a = np.arange(1,10).reshape(3,3)

In [41]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
np.diag(a)      # 대각선 성분만 추출

array([1, 5, 9])