broadcasting : 배열의 구조를 동일하게 맞춰 준다... ????

- shape이 다른 배열 간에 연산을 지원하는 기능이다!!

In [2]:
import numpy as np
a = np.array([[0,0,0], [10,10,10], [20,20,20],[30,30,30]])

In [3]:
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [4]:
a + 10

array([[10, 10, 10],
       [20, 20, 20],
       [30, 30, 30],
       [40, 40, 40]])

In [5]:
b = np.array([0, 1, 2])

In [6]:
b

array([0, 1, 2])

In [7]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

In [8]:
c = np.array([[0],[10],[20],[30]]) 

In [9]:
c

array([[ 0],
       [10],
       [20],
       [30]])

In [10]:
c.shape

(4, 1)

In [11]:
b.shape

(3,)

In [12]:
c + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

bool array , masking operation 수행할 수 있다.

In [13]:
a = np.random.randint(1, 10, (3,4))

In [14]:
a

array([[8, 8, 2, 1],
       [8, 4, 6, 1],
       [8, 3, 5, 5]])

In [15]:
a > 5

array([[ True,  True, False, False],
       [ True, False,  True, False],
       [ True, False, False, False]])

In [16]:
b = a>5

In [17]:
b

array([[ True,  True, False, False],
       [ True, False,  True, False],
       [ True, False, False, False]])

In [19]:
c = np.logical_and(a > 3, a <8)

In [20]:
c

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False,  True,  True]])

In [21]:
a

array([[8, 8, 2, 1],
       [8, 4, 6, 1],
       [8, 3, 5, 5]])

In [25]:
np.sum(a>3, axis = 1)

array([2, 3, 3])

In [26]:
np.sum(a>3)

8

In [27]:
a>3

array([[ True,  True, False, False],
       [ True,  True,  True, False],
       [ True, False,  True,  True]])

boolean index

- 특정 조건을 만족하는 값을 추출할 때 사용합니다!

In [28]:
a[a>3]

array([8, 8, 8, 4, 6, 8, 5, 5])

In [29]:
c

array([[False, False, False, False],
       [False,  True,  True, False],
       [False, False,  True,  True]])

In [30]:
a[c]

array([4, 6, 5, 5])

In [31]:
a = np.random.randint(0,100,100).reshape(10, -1)

In [32]:
a

array([[58, 91, 81, 72, 51, 75, 63, 71, 58, 60],
       [79, 95, 23,  3, 11, 18, 40, 12, 33, 12],
       [90, 46, 86,  3, 21, 80, 29, 25, 36, 90],
       [56, 71, 96, 13, 25, 13, 42, 21, 90, 86],
       [91, 65, 32,  6, 24, 44, 43, 91, 58, 11],
       [26, 64,  1, 19, 51, 38, 59, 10, 96, 47],
       [90, 84, 67, 90, 17,  5, 34, 90,  3, 81],
       [50,  0, 80, 92, 65, 17, 76, 65, 16, 86],
       [37, 39, 19, 31, 23,  8, 38, 95, 68, 38],
       [ 3, 16, 56, 30, 81, 86, 86, 35, 17, 49]])

In [33]:
b = a>50

In [34]:
b

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True, False, False, False, False, False, False, False,
        False],
       [ True, False,  True, False, False,  True, False, False, False,
         True],
       [ True,  True,  True, False, False, False, False, False,  True,
         True],
       [ True,  True, False, False, False, False, False,  True,  True,
        False],
       [False,  True, False, False,  True, False,  True, False,  True,
        False],
       [ True,  True,  True,  True, False, False, False,  True, False,
         True],
       [False, False,  True,  True,  True, False,  True,  True, False,
         True],
       [False, False, False, False, False, False, False,  True,  True,
        False],
       [False, False,  True, False,  True,  True,  True, False, False,
        False]])

In [35]:
np.sum(b)

47

In [36]:
b.astype(np.int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 0, 1, 0, 0, 0, 1],
       [1, 1, 1, 0, 0, 0, 0, 0, 1, 1],
       [1, 1, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 1, 0, 0, 1, 0, 1, 0, 1, 0],
       [1, 1, 1, 1, 0, 0, 0, 1, 0, 1],
       [0, 0, 1, 1, 1, 0, 1, 1, 0, 1],
       [0, 0, 0, 0, 0, 0, 0, 1, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 0, 0]])

In [37]:
a[ a>50]

array([58, 91, 81, 72, 51, 75, 63, 71, 58, 60, 79, 95, 90, 86, 80, 90, 56,
       71, 96, 90, 86, 91, 65, 91, 58, 64, 51, 59, 96, 90, 84, 67, 90, 90,
       81, 80, 92, 65, 76, 65, 86, 95, 68, 56, 81, 86, 86])

In [38]:
np.sum(a>50)

47

In [39]:
np.sum(a[a>50])

3612

Fancy index

- numpy array를 index value로 사용해서 값을 추출

In [40]:
a = np.arange(12).reshape(3,4)

In [41]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [42]:
row = np.array([0,1,2])

In [43]:
col = np.array([1,2,3])

In [44]:
a[row]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [45]:
a[0]

array([0, 1, 2, 3])

In [46]:
a[1]

array([4, 5, 6, 7])

In [47]:
a[2]

array([ 8,  9, 10, 11])

In [48]:
row2 = np.array([1,2])

In [49]:
a[row2]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [50]:
a[row, col]

array([ 1,  6, 11])

In [51]:
a[row2, col]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (2,) (3,) 

In [52]:
a.take(row)

array([0, 1, 2])

In [53]:
a[row]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [54]:
row3 = np.array([4,7,8])

In [56]:
a[row3]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [57]:
a.take(row3)

array([4, 7, 8])

In [58]:
c = np.random.randint(0,10, 20)

In [59]:
c

array([4, 4, 9, 1, 0, 8, 9, 9, 6, 2, 8, 3, 0, 5, 6, 0, 9, 0, 6, 4])

In [60]:
c[row3]

array([0, 9, 6])

In [61]:
c.take(row3)

array([0, 9, 6])

단위행렬 : identity

In [62]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

단축키 : 실행 (shift + enter, ctrl + enter)

함수의 설명을 볼 수 있는 단축키 : shift + tab

In [63]:
np.identity(3, dtype=np.int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [64]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [66]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [67]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [68]:
np.eye(6, k=2) # k 값을 조정해서 시작 인덱스를 변경할 수 있다!

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [69]:
np.eye(6, k = -1)

array([[0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [70]:
a = np.arange(1,10).reshape(3,3)

In [71]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
c=np.diag(a)

In [76]:
c

array([1, 5, 9])

In [77]:
c = c[::-1]

In [78]:
c

array([9, 5, 1])

In [73]:
np.diag(a, k = 1)

array([2, 6])

In [74]:
np.diag(a, k = -1)

array([4, 8])

traspose 또는 T 를 사용해서 전치행렬을 만들수 있다.

In [79]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [81]:
a.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [82]:
b = np.arange(1,7).reshape(2,3)

In [83]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [84]:
b.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [85]:
b.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [86]:
a.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [87]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [88]:
a = np.random.randint(1,7,100).reshape(10,-1)

In [89]:
a

array([[5, 2, 2, 1, 4, 2, 3, 2, 4, 5],
       [5, 5, 5, 5, 1, 6, 3, 6, 3, 5],
       [3, 2, 1, 1, 2, 3, 1, 4, 3, 1],
       [4, 1, 4, 2, 5, 1, 3, 3, 2, 2],
       [3, 3, 3, 3, 2, 5, 6, 5, 2, 3],
       [4, 1, 4, 4, 1, 1, 1, 1, 4, 4],
       [2, 6, 2, 1, 5, 3, 1, 5, 4, 6],
       [5, 2, 4, 3, 6, 6, 2, 5, 6, 1],
       [6, 6, 4, 2, 1, 4, 6, 2, 1, 3],
       [4, 4, 2, 2, 1, 6, 5, 2, 4, 3]])

In [91]:
a > 3

array([[ True, False, False, False,  True, False, False, False,  True,
         True],
       [ True,  True,  True,  True, False,  True, False,  True, False,
         True],
       [False, False, False, False, False, False, False,  True, False,
        False],
       [ True, False,  True, False,  True, False, False, False, False,
        False],
       [False, False, False, False, False,  True,  True,  True, False,
        False],
       [ True, False,  True,  True, False, False, False, False,  True,
         True],
       [False,  True, False, False,  True, False, False,  True,  True,
         True],
       [ True, False,  True, False,  True,  True, False,  True,  True,
        False],
       [ True,  True,  True, False, False,  True,  True, False, False,
        False],
       [ True,  True, False, False, False,  True,  True, False,  True,
        False]])

In [95]:
np.any(a>2, axis =0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [96]:
np.all(a>1, axis=0)

array([ True, False, False, False, False, False, False, False, False,
       False])

In [98]:
np.all(a>1, axis=1)

array([False, False, False, False,  True, False, False, False, False,
       False])

In [99]:
a = np.random.randint(1,6,9).reshape(3,3)

In [100]:
a

array([[1, 3, 2],
       [3, 1, 3],
       [2, 1, 4]])

In [102]:
np.where(a>2, 10, -10)

array([[-10,  10, -10],
       [ 10, -10,  10],
       [-10, -10,  10]])

In [103]:
np.where(a>2)

(array([0, 1, 1, 2], dtype=int64), array([1, 0, 2, 2], dtype=int64))

In [104]:
a = np.random.randint(1,6,9)

In [105]:
a

array([1, 3, 2, 1, 3, 2, 3, 3, 2])

In [106]:
np.where(a>2)

(array([1, 4, 6, 7], dtype=int64),)

In [107]:
np.isnan(a) # NaN , not a number

array([False, False, False, False, False, False, False, False, False])

In [108]:
np.isfinite(a)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

argmax, argmin 함수 : 최대값, 최소값을 가진 index 반환

In [111]:
a = np.random.randint(0,100, 20)

In [112]:
a

array([46, 38, 48, 23, 46,  7, 55, 67, 34, 26, 17, 12, 46, 54, 34, 49, 56,
       72, 72, 76])

In [113]:
np.max(a)

76

In [114]:
np.min(a)

7

In [115]:
np.argmax(a)

19

In [116]:
np.argmin(a)

5

In [117]:
b = np.random.randint(1,100,12).reshape(3,4)

In [118]:
b

array([[32, 47, 14, 28],
       [26, 36, 75, 46],
       [13, 50, 23, 16]])

In [119]:
np.argmax(b)

6

In [120]:
np.max(b)

75

In [121]:
np.argmax(b, axis=0)

array([0, 2, 1, 1], dtype=int64)

In [122]:
np.argmax(b, axis = 1)

array([1, 2, 1], dtype=int64)

In [125]:
a = np.arange(0,10).reshape(5,-1)

In [126]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [127]:
np.delete(a, 2, axis = 0)

array([[0, 1],
       [2, 3],
       [6, 7],
       [8, 9]])

In [128]:
np.delete(a, 1, axis = 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

file 입출력

In [129]:
a = np.random.randint(0,100,100).reshape(10,-1)

In [130]:
a

array([[85, 37, 57, 79, 48, 72, 75, 69,  7, 96],
       [13, 29, 58, 29,  2, 80, 37, 89, 22, 50],
       [25, 23, 87, 19, 71, 86, 23, 91,  1,  5],
       [42, 27, 16, 35, 33, 17, 85,  0, 47, 38],
       [25, 94, 98, 45, 74, 87, 45, 55, 84, 87],
       [77, 29, 14,  0, 20, 50, 50, 52, 97, 23],
       [77, 97, 88, 95, 87, 34, 53, 36, 25, 90],
       [81, 80, 68,  8, 43, 66, 35, 75,  5, 46],
       [28, 15, 98, 94,  9,  1, 63, 23, 19, 85],
       [ 9, 37, 44, 45, 56, 13, 43,  9, 42, 39]])

In [132]:
np.savetxt('savedata.csv', a, delimiter = ',' , fmt='%d')

In [136]:
b = np.loadtxt('savedata.csv', delimiter = ',', dtype=int)

In [137]:
b

array([[85, 37, 57, 79, 48, 72, 75, 69,  7, 96],
       [13, 29, 58, 29,  2, 80, 37, 89, 22, 50],
       [25, 23, 87, 19, 71, 86, 23, 91,  1,  5],
       [42, 27, 16, 35, 33, 17, 85,  0, 47, 38],
       [25, 94, 98, 45, 74, 87, 45, 55, 84, 87],
       [77, 29, 14,  0, 20, 50, 50, 52, 97, 23],
       [77, 97, 88, 95, 87, 34, 53, 36, 25, 90],
       [81, 80, 68,  8, 43, 66, 35, 75,  5, 46],
       [28, 15, 98, 94,  9,  1, 63, 23, 19, 85],
       [ 9, 37, 44, 45, 56, 13, 43,  9, 42, 39]])

In [149]:
dataFileName = 'new_daegu_temp.csv'
tempdata = np.loadtxt(dataFileName, delimiter = ',')

In [147]:
def genNewTempDataFile():
    dataFileName = 'daegu_temp_20years.csv'
    newFileName = 'new_daegu_temp.csv'
    
    read_f = open(dataFileName, 'r')
    write_f = open(newFileName, 'w')
    
    while True:
        line = read_f.readline()
        if not line:
            break
        
        splitData = line.split(',')
        
        skipWriting = False
        if len(splitData) == 5 and splitData[1].isnumeric():
            splitData[0] = splitData[0].replace('-', '')
            
            for data in splitData:
                try:
                    float(data)
                except ValueError:
                    print("에러 : ", splitData[0])
                    skipWriting = True
                    break
                    
            if not skipWriting:
                newData = ','.join(splitData)
                write_f.write(newData)

    write_f.close()
    read_f.close()
            


In [148]:
genNewTempDataFile()

에러 :  20130930
에러 :  20170729


In [150]:
tempdata.size

36665

In [151]:
tempdata.ndim

2

In [152]:
tempdata.shape

(7333, 5)